export type QuestionOption = 'a' | 'b' | 'c' | 'd';

export interface SeedQuestion {
  prompt: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: QuestionOption;
  explanation: string;
  category: 'logic' | 'patterns' | 'math' | 'general' | 'technology' | 'crypto';
  difficulty: 1 | 2 | 3 | 4 | 5;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // ---------------------------------------------------------------- patterns
  {
    prompt: 'What number comes next: 2, 4, 8, 16, ?',
    optionA: '20',
    optionB: '24',
    optionC: '32',
    optionD: '64',
    correctOption: 'c',
    explanation: 'Each term doubles the previous one, so 16 × 2 = 32.',
    category: 'patterns',
    difficulty: 1,
  },
  {
    prompt: 'What number comes next: 1, 1, 2, 3, 5, 8, ?',
    optionA: '11',
    optionB: '13',
    optionC: '14',
    optionD: '16',
    correctOption: 'b',
    explanation: 'Fibonacci: each term is the sum of the previous two, so 5 + 8 = 13.',
    category: 'patterns',
    difficulty: 1,
  },
  {
    prompt: 'What number comes next: 3, 6, 11, 18, 27, ?',
    optionA: '35',
    optionB: '36',
    optionC: '38',
    optionD: '40',
    correctOption: 'c',
    explanation: 'Differences grow by two each step (3, 5, 7, 9, 11), so 27 + 11 = 38.',
    category: 'patterns',
    difficulty: 3,
  },
  {
    prompt: 'What number comes next: 1, 4, 9, 16, 25, ?',
    optionA: '30',
    optionB: '32',
    optionC: '36',
    optionD: '49',
    correctOption: 'c',
    explanation: 'These are perfect squares; the next is 6² = 36.',
    category: 'patterns',
    difficulty: 1,
  },
  {
    prompt: 'What number comes next: 100, 50, 25, 12.5, ?',
    optionA: '10',
    optionB: '6.25',
    optionC: '5',
    optionD: '0',
    correctOption: 'b',
    explanation: 'Each term is halved, so 12.5 ÷ 2 = 6.25.',
    category: 'patterns',
    difficulty: 1,
  },
  {
    prompt: 'Which letter comes next: A, C, F, J, ?',
    optionA: 'M',
    optionB: 'N',
    optionC: 'O',
    optionD: 'P',
    correctOption: 'c',
    explanation: 'Gaps grow by one letter (1, 2, 3, 4), and J + 5 = O.',
    category: 'patterns',
    difficulty: 3,
  },
  {
    prompt: 'What number comes next: 2, 3, 5, 7, 11, ?',
    optionA: '12',
    optionB: '13',
    optionC: '14',
    optionD: '15',
    correctOption: 'b',
    explanation: 'These are the prime numbers in order; 13 follows 11.',
    category: 'patterns',
    difficulty: 2,
  },
  {
    prompt: 'What number comes next: 1, 8, 27, 64, ?',
    optionA: '81',
    optionB: '100',
    optionC: '125',
    optionD: '128',
    correctOption: 'c',
    explanation: 'These are cubes; the next is 5³ = 125.',
    category: 'patterns',
    difficulty: 2,
  },
  {
    prompt: 'What number comes next: 31, 28, 31, 30, ?',
    optionA: '28',
    optionB: '29',
    optionC: '30',
    optionD: '31',
    correctOption: 'd',
    explanation: 'These are the day counts of January to April, so May has 31 days.',
    category: 'patterns',
    difficulty: 4,
  },
  {
    prompt: 'Which value breaks the pattern: 4, 9, 16, 24, 36?',
    optionA: '9',
    optionB: '16',
    optionC: '24',
    optionD: '36',
    correctOption: 'c',
    explanation: 'All others are perfect squares; 24 is not.',
    category: 'patterns',
    difficulty: 2,
  },
  {
    prompt: 'What number comes next: 7, 14, 28, 56, ?',
    optionA: '84',
    optionB: '98',
    optionC: '112',
    optionD: '124',
    correctOption: 'c',
    explanation: 'Each term doubles, so 56 × 2 = 112.',
    category: 'patterns',
    difficulty: 1,
  },
  {
    prompt: 'What number comes next: 81, 27, 9, 3, ?',
    optionA: '0',
    optionB: '1',
    optionC: '2',
    optionD: '1.5',
    correctOption: 'b',
    explanation: 'Each term is divided by three, so 3 ÷ 3 = 1.',
    category: 'patterns',
    difficulty: 1,
  },
  {
    prompt: 'What number comes next: 2, 6, 12, 20, 30, ?',
    optionA: '36',
    optionB: '40',
    optionC: '42',
    optionD: '44',
    correctOption: 'c',
    explanation: 'The terms are n(n+1); for n = 6 that is 42.',
    category: 'patterns',
    difficulty: 3,
  },
  {
    prompt: 'Which comes next: ZA, YB, XC, ?',
    optionA: 'WD',
    optionB: 'WE',
    optionC: 'VD',
    optionD: 'XD',
    correctOption: 'a',
    explanation: 'The first letter moves backwards and the second forwards, giving WD.',
    category: 'patterns',
    difficulty: 3,
  },
  {
    prompt: 'What number comes next: 1, 2, 6, 24, ?',
    optionA: '48',
    optionB: '96',
    optionC: '120',
    optionD: '720',
    correctOption: 'c',
    explanation: 'These are factorials; 5! = 120.',
    category: 'patterns',
    difficulty: 3,
  },
  {
    prompt: 'What number comes next: 9, 16, 25, 36, ?',
    optionA: '42',
    optionB: '45',
    optionC: '49',
    optionD: '54',
    correctOption: 'c',
    explanation: 'Squares of 3, 4, 5, 6; next is 7² = 49.',
    category: 'patterns',
    difficulty: 1,
  },
  {
    prompt: 'What number comes next: 5, 11, 23, 47, ?',
    optionA: '71',
    optionB: '87',
    optionC: '94',
    optionD: '95',
    correctOption: 'd',
    explanation: 'Each term doubles and adds one: 47 × 2 + 1 = 95.',
    category: 'patterns',
    difficulty: 4,
  },
  {
    prompt: 'What number comes next: 144, 121, 100, 81, ?',
    optionA: '49',
    optionB: '60',
    optionC: '64',
    optionD: '72',
    correctOption: 'c',
    explanation: 'Descending squares of 12, 11, 10, 9; next is 8² = 64.',
    category: 'patterns',
    difficulty: 2,
  },

  // ------------------------------------------------------------------- logic
  {
    prompt: 'All roses are flowers. Some flowers fade quickly. Which statement must be true?',
    optionA: 'All roses fade quickly',
    optionB: 'Some roses fade quickly',
    optionC: 'No roses fade quickly',
    optionD: 'None of these must be true',
    correctOption: 'd',
    explanation: 'The fading flowers need not include any roses, so nothing follows necessarily.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'If it rains, the match is cancelled. The match was not cancelled. What follows?',
    optionA: 'It rained',
    optionB: 'It did not rain',
    optionC: 'It may have rained',
    optionD: 'Nothing follows',
    correctOption: 'b',
    explanation: 'Denying the consequent (modus tollens) gives "it did not rain".',
    category: 'logic',
    difficulty: 2,
  },
  {
    prompt: 'A bat and a ball cost 1.10 together. The bat costs 1.00 more than the ball. What does the ball cost?',
    optionA: '0.01',
    optionB: '0.05',
    optionC: '0.10',
    optionD: '0.11',
    correctOption: 'b',
    explanation: 'Ball 0.05 and bat 1.05 differ by exactly 1.00 and total 1.10.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'Five machines make five widgets in five minutes. How long do 100 machines take to make 100 widgets?',
    optionA: '5 minutes',
    optionB: '20 minutes',
    optionC: '100 minutes',
    optionD: '500 minutes',
    correctOption: 'a',
    explanation: 'Each machine makes one widget in five minutes, so the rate is unchanged.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'A lily patch doubles daily and covers the lake on day 48. When did it cover half the lake?',
    optionA: 'Day 12',
    optionB: 'Day 24',
    optionC: 'Day 46',
    optionD: 'Day 47',
    correctOption: 'd',
    explanation: 'Doubling means the day before full coverage it covered half.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'Some programmers drink coffee. All coffee drinkers sleep late. Which must be true?',
    optionA: 'All programmers sleep late',
    optionB: 'Some programmers sleep late',
    optionC: 'No programmer sleeps late',
    optionD: 'All late sleepers are programmers',
    correctOption: 'b',
    explanation: 'The programmers who drink coffee must sleep late.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'You have 3 red and 3 blue socks in a drawer. How many must you draw in the dark to guarantee a pair?',
    optionA: '2',
    optionB: '3',
    optionC: '4',
    optionD: '6',
    correctOption: 'b',
    explanation: 'With two colours, three socks guarantee two of the same colour.',
    category: 'logic',
    difficulty: 2,
  },
  {
    prompt: 'If no A is B and all C are B, what follows?',
    optionA: 'All C are A',
    optionB: 'Some C are A',
    optionC: 'No C is A',
    optionD: 'Nothing follows',
    correctOption: 'c',
    explanation: 'Every C is a B, and no B is an A, so no C can be an A.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'Anna is taller than Bea. Cara is shorter than Bea. Who is tallest?',
    optionA: 'Anna',
    optionB: 'Bea',
    optionC: 'Cara',
    optionD: 'Cannot be determined',
    correctOption: 'a',
    explanation: 'The ordering is Anna > Bea > Cara.',
    category: 'logic',
    difficulty: 1,
  },
  {
    prompt: 'A statement and its contrapositive are always...',
    optionA: 'Logically equivalent',
    optionB: 'Opposites',
    optionC: 'Unrelated',
    optionD: 'Both false',
    correctOption: 'a',
    explanation: '"If P then Q" and "if not Q then not P" always share a truth value.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'A clock shows 3:15. What is the angle between the hands?',
    optionA: '0 degrees',
    optionB: '7.5 degrees',
    optionC: '15 degrees',
    optionD: '30 degrees',
    correctOption: 'b',
    explanation: 'The hour hand moves a quarter past 3, giving 7.5 degrees of separation.',
    category: 'logic',
    difficulty: 4,
  },
  {
    prompt: 'Two people can paint a wall in 6 hours. How long do three equally fast people take?',
    optionA: '2 hours',
    optionB: '3 hours',
    optionC: '4 hours',
    optionD: '9 hours',
    correctOption: 'c',
    explanation: 'Total work is 12 person-hours, so three people take 4 hours.',
    category: 'logic',
    difficulty: 2,
  },
  {
    prompt: 'In a race you overtake the runner in second place. What position are you in?',
    optionA: 'First',
    optionB: 'Second',
    optionC: 'Third',
    optionD: 'Last',
    correctOption: 'b',
    explanation: 'You take the overtaken runner\u2019s place, which is second.',
    category: 'logic',
    difficulty: 2,
  },
  {
    prompt: 'Which conclusion is invalid: if P then Q, and Q is true?',
    optionA: 'P may be true',
    optionB: 'P may be false',
    optionC: 'P must be true',
    optionD: 'Q is true',
    correctOption: 'c',
    explanation: 'Affirming the consequent is a fallacy; P need not be true.',
    category: 'logic',
    difficulty: 4,
  },
  {
    prompt: 'A box has 10 balls: 6 white, 4 black. You draw one at random. Which is most likely?',
    optionA: 'White',
    optionB: 'Black',
    optionC: 'Equally likely',
    optionD: 'Cannot be determined',
    correctOption: 'a',
    explanation: 'White has probability 0.6 versus 0.4 for black.',
    category: 'logic',
    difficulty: 1,
  },
  {
    prompt: 'If every valid key opens the door and the door did not open, what follows about the key used?',
    optionA: 'It was valid',
    optionB: 'It was not valid',
    optionC: 'The door is broken',
    optionD: 'Nothing follows',
    correctOption: 'b',
    explanation: 'Contrapositive of "valid implies opens" gives "did not open implies not valid".',
    category: 'logic',
    difficulty: 2,
  },
  {
    prompt: 'Seven people each shake hands once with every other person. How many handshakes occur?',
    optionA: '14',
    optionB: '21',
    optionC: '42',
    optionD: '49',
    correctOption: 'b',
    explanation: '7 × 6 ÷ 2 = 21 distinct pairs.',
    category: 'logic',
    difficulty: 3,
  },
  {
    prompt: 'A cube is painted and cut into 27 equal small cubes. How many small cubes have no paint?',
    optionA: '0',
    optionB: '1',
    optionC: '6',
    optionD: '8',
    correctOption: 'b',
    explanation: 'Only the single centre cube has no exposed face.',
    category: 'logic',
    difficulty: 4,
  },

  // -------------------------------------------------------------------- math
  {
    prompt: 'What is 15% of 240?',
    optionA: '24',
    optionB: '30',
    optionC: '36',
    optionD: '42',
    correctOption: 'c',
    explanation: '10% is 24 and 5% is 12, so 15% is 36.',
    category: 'math',
    difficulty: 1,
  },
  {
    prompt: 'What is the value of 2^10?',
    optionA: '512',
    optionB: '1000',
    optionC: '1024',
    optionD: '2048',
    correctOption: 'c',
    explanation: '2^10 = 1024.',
    category: 'math',
    difficulty: 1,
  },
  {
    prompt: 'A price rises by 20% and then falls by 20%. Compared with the start, the final price is...',
    optionA: 'The same',
    optionB: '4% lower',
    optionC: '4% higher',
    optionD: '2% lower',
    correctOption: 'b',
    explanation: '1.2 × 0.8 = 0.96, a 4% decrease.',
    category: 'math',
    difficulty: 3,
  },
  {
    prompt: 'What is the greatest common divisor of 84 and 126?',
    optionA: '14',
    optionB: '21',
    optionC: '42',
    optionD: '63',
    correctOption: 'c',
    explanation: 'Both factor as 42 × 2 and 42 × 3, so the GCD is 42.',
    category: 'math',
    difficulty: 3,
  },
  {
    prompt: 'If 3x + 7 = 25, what is x?',
    optionA: '4',
    optionB: '5',
    optionC: '6',
    optionD: '9',
    correctOption: 'c',
    explanation: '3x = 18, so x = 6.',
    category: 'math',
    difficulty: 1,
  },
  {
    prompt: 'What is the area of a triangle with base 12 and height 7?',
    optionA: '19',
    optionB: '42',
    optionC: '76',
    optionD: '84',
    correctOption: 'b',
    explanation: 'Area = ½ × 12 × 7 = 42.',
    category: 'math',
    difficulty: 1,
  },
  {
    prompt: 'What is the sum of the integers from 1 to 100?',
    optionA: '4950',
    optionB: '5000',
    optionC: '5050',
    optionD: '10100',
    correctOption: 'c',
    explanation: '100 × 101 ÷ 2 = 5050.',
    category: 'math',
    difficulty: 2,
  },
  {
    prompt: 'What is 0.125 as a fraction in lowest terms?',
    optionA: '1/4',
    optionB: '1/6',
    optionC: '1/8',
    optionD: '1/12',
    correctOption: 'c',
    explanation: '0.125 = 125/1000 = 1/8.',
    category: 'math',
    difficulty: 1,
  },
  {
    prompt: 'A rectangle has perimeter 36 and length 12. What is its area?',
    optionA: '36',
    optionB: '60',
    optionC: '72',
    optionD: '144',
    correctOption: 'c',
    explanation: 'Width is 6, so the area is 12 × 6 = 72.',
    category: 'math',
    difficulty: 2,
  },
  {
    prompt: 'How many distinct ways can you order the letters A, B, C?',
    optionA: '3',
    optionB: '6',
    optionC: '9',
    optionD: '27',
    correctOption: 'b',
    explanation: '3! = 6 permutations.',
    category: 'math',
    difficulty: 2,
  },
  {
    prompt: 'What is the probability of rolling a total of 7 with two fair six-sided dice?',
    optionA: '1/12',
    optionB: '1/9',
    optionC: '1/6',
    optionD: '1/4',
    correctOption: 'c',
    explanation: 'Six of the thirty-six outcomes total seven.',
    category: 'math',
    difficulty: 3,
  },
  {
    prompt: 'What is the square root of 2025?',
    optionA: '35',
    optionB: '43',
    optionC: '45',
    optionD: '55',
    correctOption: 'c',
    explanation: '45 × 45 = 2025.',
    category: 'math',
    difficulty: 3,
  },
  {
    prompt: 'A shirt costs 80 after a 20% discount. What was the original price?',
    optionA: '96',
    optionB: '100',
    optionC: '104',
    optionD: '120',
    correctOption: 'b',
    explanation: '80 ÷ 0.8 = 100.',
    category: 'math',
    difficulty: 2,
  },
  {
    prompt: 'What is the median of 3, 9, 4, 1, 8?',
    optionA: '3',
    optionB: '4',
    optionC: '5',
    optionD: '8',
    correctOption: 'b',
    explanation: 'Sorted the values are 1, 3, 4, 8, 9, so the middle value is 4.',
    category: 'math',
    difficulty: 2,
  },
  {
    prompt: 'If a car travels 150 km in 2.5 hours, what is its average speed?',
    optionA: '50 km/h',
    optionB: '55 km/h',
    optionC: '60 km/h',
    optionD: '75 km/h',
    correctOption: 'c',
    explanation: '150 ÷ 2.5 = 60 km/h.',
    category: 'math',
    difficulty: 1,
  },
  {
    prompt: 'What is 7! ÷ 5!?',
    optionA: '2',
    optionB: '14',
    optionC: '35',
    optionD: '42',
    correctOption: 'd',
    explanation: '7! ÷ 5! = 7 × 6 = 42.',
    category: 'math',
    difficulty: 3,
  },
  {
    prompt: 'What is the smallest positive integer divisible by 4, 6 and 10?',
    optionA: '30',
    optionB: '40',
    optionC: '60',
    optionD: '120',
    correctOption: 'c',
    explanation: 'The least common multiple of 4, 6 and 10 is 60.',
    category: 'math',
    difficulty: 3,
  },
  {
    prompt: 'What is the value of the binary number 1011 in decimal?',
    optionA: '9',
    optionB: '11',
    optionC: '13',
    optionD: '15',
    correctOption: 'b',
    explanation: '8 + 0 + 2 + 1 = 11.',
    category: 'math',
    difficulty: 2,
  },
  {
    prompt: 'A number increased by 25% becomes 150. What is the number?',
    optionA: '110',
    optionB: '112.5',
    optionC: '120',
    optionD: '125',
    correctOption: 'c',
    explanation: '150 ÷ 1.25 = 120.',
    category: 'math',
    difficulty: 2,
  },
  {
    prompt: 'How many degrees are in the interior angles of a pentagon in total?',
    optionA: '360',
    optionB: '450',
    optionC: '540',
    optionD: '720',
    correctOption: 'c',
    explanation: '(5 − 2) × 180 = 540 degrees.',
    category: 'math',
    difficulty: 3,
  },

  // -------------------------------------------------------------- technology
  {
    prompt: 'What does HTTP status code 404 indicate?',
    optionA: 'Server error',
    optionB: 'Resource not found',
    optionC: 'Unauthorized',
    optionD: 'Redirect',
    correctOption: 'b',
    explanation: '404 means the requested resource could not be found.',
    category: 'technology',
    difficulty: 1,
  },
  {
    prompt: 'Which data structure follows last-in, first-out ordering?',
    optionA: 'Queue',
    optionB: 'Stack',
    optionC: 'Heap',
    optionD: 'Graph',
    correctOption: 'b',
    explanation: 'A stack pops the most recently pushed element first.',
    category: 'technology',
    difficulty: 1,
  },
  {
    prompt: 'What is the average time complexity of binary search on a sorted array?',
    optionA: 'O(1)',
    optionB: 'O(log n)',
    optionC: 'O(n)',
    optionD: 'O(n log n)',
    correctOption: 'b',
    explanation: 'Each comparison halves the search space.',
    category: 'technology',
    difficulty: 2,
  },
  {
    prompt: 'What does DNS translate?',
    optionA: 'Domain names to IP addresses',
    optionB: 'IP addresses to MAC addresses',
    optionC: 'URLs to HTML',
    optionD: 'Passwords to hashes',
    correctOption: 'a',
    explanation: 'The Domain Name System resolves human-readable names to IP addresses.',
    category: 'technology',
    difficulty: 1,
  },
  {
    prompt: 'How many bits are in one byte?',
    optionA: '4',
    optionB: '8',
    optionC: '16',
    optionD: '32',
    correctOption: 'b',
    explanation: 'A byte is eight bits.',
    category: 'technology',
    difficulty: 1,
  },
  {
    prompt: 'Which HTTP method is defined as idempotent and used to replace a resource?',
    optionA: 'POST',
    optionB: 'PUT',
    optionC: 'PATCH',
    optionD: 'CONNECT',
    correctOption: 'b',
    explanation: 'PUT replaces a resource and repeating it has the same effect.',
    category: 'technology',
    difficulty: 3,
  },
  {
    prompt: 'What does SQL stand for?',
    optionA: 'Structured Query Language',
    optionB: 'Sequential Query Logic',
    optionC: 'Systems Query Layer',
    optionD: 'Simple Question Language',
    correctOption: 'a',
    explanation: 'SQL is Structured Query Language.',
    category: 'technology',
    difficulty: 1,
  },
  {
    prompt: 'Which of these is a cryptographic hash function?',
    optionA: 'AES',
    optionB: 'RSA',
    optionC: 'SHA-256',
    optionD: 'TLS',
    correctOption: 'c',
    explanation: 'SHA-256 is a hash function; AES and RSA are ciphers and TLS is a protocol.',
    category: 'technology',
    difficulty: 2,
  },
  {
    prompt: 'In Git, which command creates a new branch and switches to it?',
    optionA: 'git branch -d',
    optionB: 'git checkout -b',
    optionC: 'git merge',
    optionD: 'git remote add',
    correctOption: 'b',
    explanation: 'git checkout -b creates and switches in one step.',
    category: 'technology',
    difficulty: 2,
  },
  {
    prompt: 'What is the primary purpose of an index in a relational database?',
    optionA: 'To store backups',
    optionB: 'To speed up lookups',
    optionC: 'To encrypt columns',
    optionD: 'To normalise tables',
    correctOption: 'b',
    explanation: 'Indexes accelerate read queries at the cost of write overhead and storage.',
    category: 'technology',
    difficulty: 2,
  },
  {
    prompt: 'Which port does HTTPS use by default?',
    optionA: '21',
    optionB: '80',
    optionC: '443',
    optionD: '8080',
    correctOption: 'c',
    explanation: 'HTTPS defaults to TCP port 443.',
    category: 'technology',
    difficulty: 2,
  },
  {
    prompt: 'What does an HTTP-only cookie flag prevent?',
    optionA: 'Sending the cookie over HTTP',
    optionB: 'JavaScript from reading the cookie',
    optionC: 'The cookie from expiring',
    optionD: 'Cross-origin requests',
    correctOption: 'b',
    explanation: 'HttpOnly hides the cookie from client-side scripts, mitigating XSS theft.',
    category: 'technology',
    difficulty: 3,
  },
  {
    prompt: 'Which sorting algorithm has O(n log n) worst-case time and is stable?',
    optionA: 'Quicksort',
    optionB: 'Merge sort',
    optionC: 'Selection sort',
    optionD: 'Bubble sort',
    correctOption: 'b',
    explanation: 'Merge sort is stable with O(n log n) worst-case complexity.',
    category: 'technology',
    difficulty: 3,
  },
  {
    prompt: 'What is a race condition?',
    optionA: 'A slow network request',
    optionB: 'Behaviour depending on unsynchronised timing',
    optionC: 'A compiler optimisation',
    optionD: 'A type error',
    correctOption: 'b',
    explanation: 'Outcomes depend on the relative timing of concurrent operations.',
    category: 'technology',
    difficulty: 3,
  },
  {
    prompt: 'What does an idempotency key protect against?',
    optionA: 'Slow queries',
    optionB: 'Duplicate processing of a retried request',
    optionC: 'SQL injection',
    optionD: 'Expired sessions',
    correctOption: 'b',
    explanation: 'The server recognises the repeated key and applies the effect only once.',
    category: 'technology',
    difficulty: 3,
  },
  {
    prompt: 'In TypeScript, what does the "unknown" type require before use?',
    optionA: 'A cast or narrowing check',
    optionB: 'Nothing, it behaves like any',
    optionC: 'A class declaration',
    optionD: 'A decorator',
    correctOption: 'a',
    explanation: 'unknown must be narrowed or asserted before its value can be used.',
    category: 'technology',
    difficulty: 3,
  },
  {
    prompt: 'Which status code should an API return when a rate limit is exceeded?',
    optionA: '400',
    optionB: '403',
    optionC: '429',
    optionD: '503',
    correctOption: 'c',
    explanation: '429 Too Many Requests signals rate limiting.',
    category: 'technology',
    difficulty: 3,
  },
  {
    prompt: 'What is the main benefit of a database transaction?',
    optionA: 'Faster reads',
    optionB: 'All-or-nothing atomic changes',
    optionC: 'Smaller storage',
    optionD: 'Automatic indexing',
    correctOption: 'b',
    explanation: 'Transactions commit fully or roll back entirely.',
    category: 'technology',
    difficulty: 2,
  },
  {
    prompt: 'What does UTC stand for in the context of server time?',
    optionA: 'Universal Time Code',
    optionB: 'Coordinated Universal Time',
    optionC: 'Unified Timezone Clock',
    optionD: 'Uniform Time Convention',
    correctOption: 'b',
    explanation: 'UTC is Coordinated Universal Time, the reference used for server timestamps.',
    category: 'technology',
    difficulty: 2,
  },
  {
    prompt: 'Which of these is NOT a valid JSON value?',
    optionA: 'null',
    optionB: 'true',
    optionC: 'undefined',
    optionD: '[]',
    correctOption: 'c',
    explanation: 'JSON has no undefined literal.',
    category: 'technology',
    difficulty: 2,
  },

  // ------------------------------------------------------------------ crypto
  {
    prompt: 'What is a public key used for?',
    optionA: 'Signing messages',
    optionB: 'Verifying signatures',
    optionC: 'Encrypting the private key',
    optionD: 'Storing funds offline',
    correctOption: 'b',
    explanation: 'A private key signs; the matching public key verifies.',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'What does it mean for a blockchain transaction to be "confirmed"?',
    optionA: 'It was broadcast to a node',
    optionB: 'It was included in an accepted block',
    optionC: 'The sender approved it in a wallet',
    optionD: 'The fee was paid',
    correctOption: 'b',
    explanation: 'Confirmation means inclusion in a block accepted by the network.',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'Signing a message with a wallet normally...',
    optionA: 'Transfers funds',
    optionB: 'Costs a network fee',
    optionC: 'Proves key ownership without spending',
    optionD: 'Publishes data on-chain',
    correctOption: 'c',
    explanation: 'Message signing is an off-chain proof of control and costs nothing.',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'Why do authentication challenges include a random nonce?',
    optionA: 'To compress the message',
    optionB: 'To prevent replay of an old signature',
    optionC: 'To pay for gas',
    optionD: 'To identify the device',
    correctOption: 'b',
    explanation: 'A single-use nonce makes a captured signature worthless later.',
    category: 'crypto',
    difficulty: 3,
  },
  {
    prompt: 'What is a consensus mechanism responsible for?',
    optionA: 'Agreeing on the ledger state',
    optionB: 'Encrypting wallet backups',
    optionC: 'Compressing blocks',
    optionD: 'Setting exchange rates',
    correctOption: 'a',
    explanation: 'Consensus lets distributed nodes agree on a single valid history.',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'A seed phrase should be...',
    optionA: 'Shared with support staff',
    optionB: 'Stored offline and never shared',
    optionC: 'Posted as a backup in email',
    optionD: 'Entered on any site that asks',
    correctOption: 'b',
    explanation: 'Anyone with the seed phrase controls the funds, so it must stay private.',
    category: 'crypto',
    difficulty: 1,
  },
  {
    prompt: 'What is the smallest unit of NIM called?',
    optionA: 'Satoshi',
    optionB: 'Wei',
    optionC: 'Luna',
    optionD: 'Gwei',
    correctOption: 'c',
    explanation: 'Nimiq denominates amounts in Luna; 1 NIM = 100,000 Luna.',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'How many Luna make one NIM?',
    optionA: '1,000',
    optionB: '10,000',
    optionC: '100,000',
    optionD: '100,000,000',
    correctOption: 'c',
    explanation: 'One NIM equals 100,000 Luna (five decimal places).',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'What is a hash function collision?',
    optionA: 'Two inputs producing the same output',
    optionB: 'A failed network request',
    optionC: 'A duplicate transaction fee',
    optionD: 'An invalid public key',
    correctOption: 'a',
    explanation: 'A collision is two distinct inputs with identical hash outputs.',
    category: 'crypto',
    difficulty: 3,
  },
  {
    prompt: 'Which property makes a good cryptographic hash suitable for integrity checks?',
    optionA: 'It is reversible',
    optionB: 'Small input changes change the output drastically',
    optionC: 'It always outputs short strings',
    optionD: 'It is randomised per call',
    correctOption: 'b',
    explanation: 'The avalanche effect means any modification is easily detected.',
    category: 'crypto',
    difficulty: 3,
  },
  {
    prompt: 'What does "self-custody" mean?',
    optionA: 'An exchange holds your keys',
    optionB: 'You control your own private keys',
    optionC: 'A bank insures your balance',
    optionD: 'Funds are locked in a contract',
    correctOption: 'b',
    explanation: 'Self-custody means the user, not a third party, holds the keys.',
    category: 'crypto',
    difficulty: 1,
  },
  {
    prompt: 'A blockchain address is generally derived from...',
    optionA: 'The private key only',
    optionB: 'The public key',
    optionC: 'The user email',
    optionD: 'The node IP',
    correctOption: 'b',
    explanation: 'Addresses are derived deterministically from the public key.',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'Why is a transaction fee usually required?',
    optionA: 'To reward validators and deter spam',
    optionB: 'To register the wallet',
    optionC: 'To mint new addresses',
    optionD: 'To encrypt the payload',
    correctOption: 'a',
    explanation: 'Fees compensate block producers and make spamming expensive.',
    category: 'crypto',
    difficulty: 2,
  },
  {
    prompt: 'What does a "light client" do?',
    optionA: 'Stores the full chain history',
    optionB: 'Verifies with minimal data instead of the full chain',
    optionC: 'Mines blocks on mobile',
    optionD: 'Replaces the consensus algorithm',
    correctOption: 'b',
    explanation: 'Light clients sync and verify using far less data than full nodes.',
    category: 'crypto',
    difficulty: 3,
  },
  {
    prompt: 'What is the main risk of pasting a wallet address from an untrusted source?',
    optionA: 'Higher fees',
    optionB: 'Clipboard malware may swap the address',
    optionC: 'Slower confirmation',
    optionD: 'It expires',
    correctOption: 'b',
    explanation: 'Address-swapping malware redirects funds; always verify the address.',
    category: 'crypto',
    difficulty: 3,
  },
  {
    prompt: 'On-chain transactions are best described as...',
    optionA: 'Private and reversible',
    optionB: 'Public and generally irreversible',
    optionC: 'Private and irreversible',
    optionD: 'Public and reversible',
    correctOption: 'b',
    explanation: 'Ledger entries are publicly visible and cannot normally be undone.',
    category: 'crypto',
    difficulty: 2,
  },

  // ----------------------------------------------------------------- general
  {
    prompt: 'Which planet is closest to the Sun?',
    optionA: 'Venus',
    optionB: 'Mercury',
    optionC: 'Mars',
    optionD: 'Earth',
    correctOption: 'b',
    explanation: 'Mercury orbits closest to the Sun.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'What is the largest ocean on Earth?',
    optionA: 'Atlantic',
    optionB: 'Indian',
    optionC: 'Pacific',
    optionD: 'Arctic',
    correctOption: 'c',
    explanation: 'The Pacific Ocean is the largest by area and volume.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'How many continents are there by the common seven-continent model?',
    optionA: '5',
    optionB: '6',
    optionC: '7',
    optionD: '8',
    correctOption: 'c',
    explanation: 'The seven-continent model counts seven.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'Which gas do plants absorb from the atmosphere for photosynthesis?',
    optionA: 'Oxygen',
    optionB: 'Nitrogen',
    optionC: 'Carbon dioxide',
    optionD: 'Hydrogen',
    correctOption: 'c',
    explanation: 'Plants take in carbon dioxide and release oxygen.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'What is the chemical symbol for gold?',
    optionA: 'Go',
    optionB: 'Gd',
    optionC: 'Ag',
    optionD: 'Au',
    correctOption: 'd',
    explanation: 'Gold is Au, from the Latin aurum.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'Which is the longest river in the world by most measurements?',
    optionA: 'Amazon',
    optionB: 'Nile',
    optionC: 'Yangtze',
    optionD: 'Mississippi',
    correctOption: 'b',
    explanation: 'The Nile is traditionally listed as the longest river.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'How many minutes are in a full day?',
    optionA: '1200',
    optionB: '1440',
    optionC: '1680',
    optionD: '2400',
    correctOption: 'b',
    explanation: '24 × 60 = 1440 minutes.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'Which language has the most native speakers worldwide?',
    optionA: 'English',
    optionB: 'Spanish',
    optionC: 'Mandarin Chinese',
    optionD: 'Hindi',
    correctOption: 'c',
    explanation: 'Mandarin Chinese has the largest number of native speakers.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'What is the capital of Switzerland?',
    optionA: 'Zurich',
    optionB: 'Geneva',
    optionC: 'Bern',
    optionD: 'Basel',
    correctOption: 'c',
    explanation: 'Bern is the Swiss federal city and de facto capital.',
    category: 'general',
    difficulty: 3,
  },
  {
    prompt: 'Which organ pumps blood through the human body?',
    optionA: 'Liver',
    optionB: 'Heart',
    optionC: 'Lungs',
    optionD: 'Kidney',
    correctOption: 'b',
    explanation: 'The heart circulates blood.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'Approximately how long does light take to travel from the Sun to Earth?',
    optionA: '8 seconds',
    optionB: '8 minutes',
    optionC: '8 hours',
    optionD: '8 days',
    correctOption: 'b',
    explanation: 'Sunlight takes roughly eight minutes and twenty seconds.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'Which metal is liquid at room temperature?',
    optionA: 'Mercury',
    optionB: 'Lead',
    optionC: 'Tin',
    optionD: 'Zinc',
    correctOption: 'a',
    explanation: 'Mercury is the only metal that is liquid at standard room temperature.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'How many strings does a standard guitar have?',
    optionA: '4',
    optionB: '5',
    optionC: '6',
    optionD: '7',
    correctOption: 'c',
    explanation: 'A standard guitar has six strings.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'What does the Richter scale measure?',
    optionA: 'Wind speed',
    optionB: 'Earthquake magnitude',
    optionC: 'Rainfall',
    optionD: 'Sound volume',
    correctOption: 'b',
    explanation: 'It quantifies the magnitude of earthquakes.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'Which country is home to the kangaroo?',
    optionA: 'Brazil',
    optionB: 'South Africa',
    optionC: 'Australia',
    optionD: 'Indonesia',
    correctOption: 'c',
    explanation: 'Kangaroos are native to Australia.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'What is the freezing point of water in Fahrenheit?',
    optionA: '0',
    optionB: '32',
    optionC: '64',
    optionD: '100',
    correctOption: 'b',
    explanation: 'Water freezes at 32 °F, equal to 0 °C.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'Which instrument measures atmospheric pressure?',
    optionA: 'Barometer',
    optionB: 'Thermometer',
    optionC: 'Hygrometer',
    optionD: 'Anemometer',
    correctOption: 'a',
    explanation: 'A barometer measures air pressure.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'How many sides does a hexagon have?',
    optionA: '5',
    optionB: '6',
    optionC: '7',
    optionD: '8',
    correctOption: 'b',
    explanation: 'A hexagon has six sides.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'Which vitamin is primarily produced by the skin in sunlight?',
    optionA: 'Vitamin A',
    optionB: 'Vitamin B12',
    optionC: 'Vitamin C',
    optionD: 'Vitamin D',
    correctOption: 'd',
    explanation: 'Sun exposure triggers vitamin D synthesis.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'What is the tallest mountain above sea level?',
    optionA: 'K2',
    optionB: 'Mount Everest',
    optionC: 'Denali',
    optionD: 'Mont Blanc',
    correctOption: 'b',
    explanation: 'Mount Everest is the highest point above sea level.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'Roughly what percentage of the human body is water?',
    optionA: '20%',
    optionB: '40%',
    optionC: '60%',
    optionD: '90%',
    correctOption: 'c',
    explanation: 'Around 60% of adult body mass is water.',
    category: 'general',
    difficulty: 2,
  },
  {
    prompt: 'Which sea creature has three hearts?',
    optionA: 'Dolphin',
    optionB: 'Octopus',
    optionC: 'Shark',
    optionD: 'Jellyfish',
    correctOption: 'b',
    explanation: 'An octopus has one systemic and two branchial hearts.',
    category: 'general',
    difficulty: 3,
  },
  {
    prompt: 'In which century did the first Moon landing take place?',
    optionA: '18th',
    optionB: '19th',
    optionC: '20th',
    optionD: '21st',
    correctOption: 'c',
    explanation: 'Apollo 11 landed in 1969, in the 20th century.',
    category: 'general',
    difficulty: 1,
  },
  {
    prompt: 'What is the study of fossils called?',
    optionA: 'Geology',
    optionB: 'Paleontology',
    optionC: 'Archaeology',
    optionD: 'Anthropology',
    correctOption: 'b',
    explanation: 'Paleontology studies fossilised life.',
    category: 'general',
    difficulty: 2,
  },
];
